/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AmigosRouteImport } from './routes/amigos'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ComunidadesIndexRouteImport } from './routes/comunidades.index'
import { Route as ComunidadesSlugRouteImport } from './routes/comunidades.$slug'
import { Route as PerfilIdRouteImport } from './routes/perfil.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AmigosRoute = AmigosRouteImport.update({
  id: '/amigos',
  path: '/amigos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadesIndexRoute = ComunidadesIndexRouteImport.update({
  id: '/comunidades/',
  path: '/comunidades/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadesSlugRoute = ComunidadesSlugRouteImport.update({
  id: '/comunidades/$slug',
  path: '/comunidades/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilIdRoute = PerfilIdRouteImport.update({
  id: '/perfil/$id',
  path: '/perfil/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/amigos': typeof AmigosRoute
  '/auth': typeof AuthRoute
  '/comunidades/$slug': typeof ComunidadesSlugRoute
  '/perfil/$id': typeof PerfilIdRoute
  '/comunidades/': typeof ComunidadesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/amigos': typeof AmigosRoute
  '/auth': typeof AuthRoute
  '/comunidades/$slug': typeof ComunidadesSlugRoute
  '/perfil/$id': typeof PerfilIdRoute
  '/comunidades': typeof ComunidadesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/amigos': typeof AmigosRoute
  '/auth': typeof AuthRoute
  '/comunidades/$slug': typeof ComunidadesSlugRoute
  '/perfil/$id': typeof PerfilIdRoute
  '/comunidades/': typeof ComunidadesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/amigos'
    | '/auth'
    | '/comunidades/$slug'
    | '/perfil/$id'
    | '/comunidades/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/amigos'
    | '/auth'
    | '/comunidades/$slug'
    | '/perfil/$id'
    | '/comunidades'
  id:
    | '__root__'
    | '/'
    | '/amigos'
    | '/auth'
    | '/comunidades/$slug'
    | '/perfil/$id'
    | '/comunidades/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AmigosRoute: typeof AmigosRoute
  AuthRoute: typeof AuthRoute
  ComunidadesSlugRoute: typeof ComunidadesSlugRoute
  PerfilIdRoute: typeof PerfilIdRoute
  ComunidadesIndexRoute: typeof ComunidadesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amigos': {
      id: '/amigos'
      path: '/amigos'
      fullPath: '/amigos'
      preLoaderRoute: typeof AmigosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidades/': {
      id: '/comunidades/'
      path: '/comunidades'
      fullPath: '/comunidades/'
      preLoaderRoute: typeof ComunidadesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidades/$slug': {
      id: '/comunidades/$slug'
      path: '/comunidades/$slug'
      fullPath: '/comunidades/$slug'
      preLoaderRoute: typeof ComunidadesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/$id': {
      id: '/perfil/$id'
      path: '/perfil/$id'
      fullPath: '/perfil/$id'
      preLoaderRoute: typeof PerfilIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AmigosRoute: AmigosRoute,
  AuthRoute: AuthRoute,
  ComunidadesSlugRoute: ComunidadesSlugRoute,
  PerfilIdRoute: PerfilIdRoute,
  ComunidadesIndexRoute: ComunidadesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
